apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-simple
  labels:
    app: mssql-simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mssql-simple
  template:
    metadata:
      labels:
        app: mssql-simple
    spec:
      containers:
        - name: mssql-simple
          image: mcr.microsoft.com/mssql/server
          ports:
          - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value:  "password@12345#"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service-simple
spec:
  selector:
    app: mssql-simple
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
